# ──────────────────────────────────────────────────────────────────────────────
# hosts/cleboost-sage/gpu-env.nix — PRIME / NVIDIA session environment
# card0 = NVIDIA RTX (PCI:1:0:0), card1 = AMD iGPU (PCI:6:0:0) — see nixos/nvidia.nix
# ──────────────────────────────────────────────────────────────────────────────
{ config, pkgs, lib, ... }:

let
  # Desktop apps (Chrome, games, …) — prefer NVIDIA
  appGpuEnv = {
    LIBVA_DRIVER_NAME = "nvidia";
    __GLX_VENDOR_LIBRARY_NAME = "nvidia";
    __GL_GSYNC_ALLOWED = "1";
    __GL_MaxFramesAllowed = "1";
    __GL_SHADER_DISK_CACHE = "1";
    __GL_SHADER_DISK_CACHE_SKIP_CLEANUP = "1";
    RADV_PERFTEST = "aco";
    DXVK_ASYNC = "1";
    NVD_BACKEND = "direct";
    MANGOHUD = "1";
    MANGOHUD_DLSYM = "1";
  };

  # Hyprland / Aquamarine: dGPU primary
  hyprGpuEnv = appGpuEnv // {
    WLR_DRM_DEVICES = "/dev/dri/card0:/dev/dri/card1";
    AQ_DRM_DEVICES = "/dev/dri/card0:/dev/dri/card1";
    GBM_BACKEND = "nvidia-drm";
  };

  appGpuEnvNames = lib.attrNames appGpuEnv;

  hyprLuaLines = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (n: v: ''hl.env("${n}", "${v}")'') hyprGpuEnv
  );
in
{
  home.sessionVariables = appGpuEnv;

  xdg.configFile."hypr/gpu-env.lua" = {
    text = ''
      -- Generated by hosts/cleboost-sage/gpu-env.nix — do not edit
      ${hyprLuaLines}
    '';
  };

  home.file.".local/bin/gpu-import-env" = {
    executable = true;
    text = ''
      #!${pkgs.bash}/bin/bash
      # Generated by hosts/cleboost-sage/gpu-env.nix — do not edit
      systemctl --user import-environment ${lib.concatStringsSep " " appGpuEnvNames}
    '';
  };
}
