-- Hyprland entrypoint (Lua only). See https://wiki.hypr.land/Configuring/

local home = os.getenv("HOME") or "/home/cleboost"
package.path = table.concat({
    home .. "/.config/hypr/?.lua",
    home .. "/.config/hypr/?/init.lua",
    package.path,
}, ";")

-- ── Core ──────────────────────────────────────────────────────────────────────
require("gpu-env")
require("core.env")
require("core.general")
require("core.monitors")
pcall(require, "workspaces") -- generated by scripts/manage_workspaces.sh
require("core.execs")

-- ── Appearance ────────────────────────────────────────────────────────────────
require("theme.colors")

-- ── Binds ─────────────────────────────────────────────────────────────────────
require("binds.noctalia")
require("binds.workspaces")
require("binds.keybinds")

-- ── Rules ─────────────────────────────────────────────────────────────────────
require("rules.rules")
require("rules.specialwork")

-- ── Noctalia theme (writes ~/.config/hypr/noctalia.lua) ───────────────────────
pcall(function()
    require("noctalia").apply_theme()
end)

-- ── Personal overrides (last) ─────────────────────────────────────────────────
require("custom")

-- Noctalia catch-all submap — required for keybinds to work
hl.dispatch(hl.dsp.submap("global"))
