# #######################################################################################
# 🎨  THEME & COLORS
# #######################################################################################

##! Borders & Background
general {
    col.active_border = rgba(91909177)
    col.inactive_border = rgba(47474855)
}

misc {
    background_color = rgba(131314FF)
}

##! Hyprbars (Optional Plugin)
# plugin {
#     hyprbars {
#         bar_text_font = Google Sans Flex Medium, Rubik, sans-serif
#         bar_height = 30
#         bar_color = rgba(131314FF)
#         col.text = rgba(e4e2e3FF)
#     }
# }
