# #######################################################################################
#   SPECIAL WORKSPACES (COMM & MUSIC)
# #######################################################################################

##! Window Rules (Direct assignment)
windowrule = match:class ^(discord)$, workspace special:comm silent
windowrule = match:class ^(discord)$, no_initial_focus on
windowrule = match:class ^(Spotify)$, workspace special:music silent
windowrule = match:class ^(Spotify)$, no_initial_focus on

##! Workspace Configuration
workspace = special:music, gapsout:50
workspace = special:comm, gapsout:50

##! Autostart
exec-once = discord
exec-once = spotify