
# =============  Noctalia SHELL keybinds (V5) ============
bind = Ctrl+Super, T, exec, noctalia msg panel-toggle wallpaper # Toggle wallpaper selector
bind = Ctrl+Super+Alt, T, exec, noctalia msg wallpaper-random # Random wallpaper

bind = Super, Super_L, exec, noctalia msg panel-toggle launcher # Launcher
bind = Super, Super_R, exec, noctalia msg panel-toggle launcher # Launcher

bindd = Ctrl+Super+Alt, R, Restart shell, exec, pkill noctalia; noctalia # Restart the shell
bindd = Ctrl+Shift+Super+Alt, R, Restart shell, exec, pkill noctalia # Kill the shell

bind = SUPER, comma, exec, noctalia msg settings-toggle # Settings Panel
bind = Ctrl+Alt, Delete, exec, noctalia msg panel-toggle session # Session menu
bindd = Super, V, Clipboard history, exec, noctalia msg panel-toggle clipboard # Clipboard history

bind = Super, mouse:275, exec, noctalia msg media previous # Super + mouse back = previous track
bind = Super, mouse:276, exec, noctalia msg media next # Super + mouse forward = next track

bindle = ,XF86AudioRaiseVolume, exec, noctalia msg volume-up # Volume up
bindle = ,XF86AudioLowerVolume, exec, noctalia msg volume-down # Volume down
bindl = ,XF86AudioMicMute, exec, noctalia msg mic-mute # Mute mic
bindl = ,XF86AudioMute, exec, noctalia msg volume-mute # Mute/unmute volume

bindle= ,XF86MonBrightnessDown, exec, noctalia msg brightness-down
bindle= ,XF86MonBrightnessUp, exec, noctalia msg brightness-up

bindd = Super, L, Lock, exec, noctalia msg screen-lock

# ==============  OLD Noctalia SHELL compatibility keybinds (V4)============
#bind = Super, R, exec, qs -c noctalia-shell ipc call plugin:screen-recorder toggle
#bind = Super, F5, exec, qs -c noctalia-shell ipc call powerProfile cycle # Cycle power profile
#binde = Super, Minus, exec, qs -c $qsConfig ipc call TEST_ALIVE || ~/.config/hypr/hyprland/scripts/zoom.sh decrease 0.1 # [hidden] Zoom out
#binde = Super, Equal, exec, qs -c $qsConfig ipc call TEST_ALIVE || ~/.config/hypr/hyprland/scripts/zoom.sh increase 0.1 # [hidden] Zoom in
#binde = Super, code:82, exec, qs -c $qsConfig ipc call TEST_ALIVE || ~/.config/hypr/hyprland/scripts/zoom.sh decrease 0.1 # [hidden] Zoom out
#binde = Super, code:86, exec, qs -c $qsConfig ipc call TEST_ALIVE || ~/.config/hypr/hyprland/scripts/zoom.sh increase 0.1 # [hidden] Zoom in
