[audio]
enable_sounds = true

[bar]
order = [ "main" ]

    [bar.main]
    background_opacity = 1.0
    center = [ "workspaces" ]
    end = [ "tray", "notifications", "network", "battery", "control-center", "session" ]
    radius = 80
    start = [ "media", "clock", "cpu", "ram", "temp" ]

[brightness]
enable_ddcutil = true

[nightlight]
enabled = false

[shell]
avatar_path = "/home/cleboost/Pictures/profile.png"
polkit_agent = true
settings_show_advanced = false
telemetry_enabled = true
ui_scale = 1.0

    [shell.animation]
    enabled = true

[theme]
builtin = "Noctalia"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "kitty", "hyprland" ]

[wallpaper]
directory = "/home/cleboost/Pictures/Wallpapers"
transition = [ "disc", "stripes", "zoom" ]

    [wallpaper.default]
    path = "/home/cleboost/Pictures/Wallpapers/1304710.jpg"

    [wallpaper.monitors.DP-2]
    path = "/home/cleboost/Pictures/Wallpapers/1304710.jpg"

    [wallpaper.monitors.DP-3]
    path = "/home/cleboost/Pictures/Wallpapers/1304710.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/cleboost/Pictures/Wallpapers/1304710.jpg"

[weather]
address = "Mercurol"
enabled = true

[widget.cpu]
display = "gauge"
show_label = true
type = "sysmon"

[widget.media]
capsule = false

[widget.scripted]
capsule = false

[widget.sysmon]
stat = "cpu_usage"

[widget.workspaces]
display = "none"