# Single source of truth for PRIME / NVIDIA session environment.
# card0 = NVIDIA RTX (PCI:1:0:0), card1 = AMD iGPU (PCI:6:0:0) — see modules/nvidia.nix
{ config, pkgs, lib, ... }:

let
  # Apps (Chrome, games, etc.) — always prefer NVIDIA.
  appGpuEnv = {
    LIBVA_DRIVER_NAME = "nvidia";
    __GLX_VENDOR_LIBRARY_NAME = "nvidia";
    __GL_GSYNC_ALLOWED = "1";
    __GL_MaxFramesAllowed = "1";
    NVD_BACKEND = "direct";
    MANGOHUD = "1";
    MANGOHUD_DLSYM = "1";
  };

  # Hyprland / Aquamarine: dGPU primary, handles PRIME cross-GPU differently than wlroots.
  hyprGpuEnv = appGpuEnv // {
    WLR_DRM_DEVICES = "/dev/dri/card0:/dev/dri/card1";
    AQ_DRM_DEVICES = "/dev/dri/card0:/dev/dri/card1";
    GBM_BACKEND = "nvidia-drm";
  };

  # Umbriel / wlroots: render on AMD (eDP), scan out externals on NVIDIA via PRIME copy.
  # GBM_BACKEND=nvidia-drm here breaks eDP with "Failed to pick primary buffer format".
  umbrielCompositorEnv = {
    WLR_DRM_DEVICES = "/dev/dri/card1:/dev/dri/card0";
  };

  appGpuEnvNames = lib.attrNames appGpuEnv;

  hyprConfLines = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (n: v: "env = ${n}, ${v}") hyprGpuEnv
  );

  hyprLuaLines = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (n: v: ''hl.env("${n}", "${v}")'') hyprGpuEnv
  );

  umbrielTomlLines = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (n: v: "${n} = \"${v}\"") umbrielCompositorEnv
  );
in
{
  home.sessionVariables = appGpuEnv;

  xdg.configFile."hypr/gpu-env.conf" = {
    text = ''
      # Generated by home/modules/gpu-env.nix — do not edit
      ${hyprConfLines}
    '';
  };

  xdg.configFile."hypr/gpu-env.lua" = {
    text = ''
      -- Generated by home/modules/gpu-env.nix — do not edit
      ${hyprLuaLines}
    '';
  };

  xdg.configFile."umbriel/gpu-env.toml" = {
    text = ''
      # Generated by home/modules/gpu-env.nix — do not edit
      [environment]
      ${umbrielTomlLines}
    '';
  };

  home.file.".local/bin/gpu-import-env" = {
    executable = true;
    text = ''
      #!${pkgs.bash}/bin/bash
      # Generated by home/modules/gpu-env.nix — do not edit
      systemctl --user import-environment ${lib.concatStringsSep " " appGpuEnvNames}
    '';
  };
}
