# Single source of truth for PRIME / NVIDIA session environment.
# card0 = NVIDIA RTX (PCI:1:0:0), card1 = AMD iGPU (PCI:6:0:0) — see modules/nvidia.nix
{ config, pkgs, lib, ... }:

let
  gpuEnv = {
    WLR_DRM_DEVICES = "/dev/dri/card0:/dev/dri/card1";
    AQ_DRM_DEVICES = "/dev/dri/card0:/dev/dri/card1";
    LIBVA_DRIVER_NAME = "nvidia";
    __GLX_VENDOR_LIBRARY_NAME = "nvidia";
    GBM_BACKEND = "nvidia-drm";
    __GL_GSYNC_ALLOWED = "1";
    __GL_MaxFramesAllowed = "1";
    NVD_BACKEND = "direct";
    MANGOHUD = "1";
    MANGOHUD_DLSYM = "1";
  };

  # Hyprland (Aquamarine) + Umbriel (wlroots) share the same values; only the key name differs.
  umbrielGpuEnv = lib.filterAttrs (name: _: name != "AQ_DRM_DEVICES") gpuEnv;

  gpuEnvNames = lib.attrNames umbrielGpuEnv;

  hyprConfLines = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (n: v: "env = ${n}, ${v}") gpuEnv
  );

  hyprLuaLines = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (n: v: ''hl.env("${n}", "${v}")'') gpuEnv
  );

  umbrielTomlLines = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (n: v: "${n} = \"${v}\"") umbrielGpuEnv
  );
in
{
  home.sessionVariables = umbrielGpuEnv;

  xdg.configFile."hypr/gpu-env.conf" = {
    text = ''
      # Generated by home/modules/gpu-env.nix — do not edit
      ${hyprConfLines}
    '';
  };

  xdg.configFile."hypr/gpu-env.lua" = {
    text = ''
      -- Generated by home/modules/gpu-env.nix — do not edit
      ${hyprLuaLines}
    '';
  };

  xdg.configFile."umbriel/gpu-env.toml" = {
    text = ''
      # Generated by home/modules/gpu-env.nix — do not edit
      [environment]
      ${umbrielTomlLines}
    '';
  };

  home.file.".local/bin/gpu-import-env" = {
    executable = true;
    text = ''
      #!${pkgs.bash}/bin/bash
      # Generated by home/modules/gpu-env.nix — do not edit
      systemctl --user import-environment ${lib.concatStringsSep " " gpuEnvNames}
    '';
  };
}
