### MangoHud Configuration for Gaming & 1% Low monitoring

# Affichage FPS & 1% low (critique pour mesurer la fluidité)
fps
fps_metrics=avg,0.01
frametime
frame_timing=1

# Stats GPU & CPU
gpu_stats
gpu_temp
gpu_core_clock
gpu_power

cpu_stats
cpu_temp
cpu_mhz

# Mémoire
vram
ram

# Options visuelles
position=top-left
round_corners=10
background_alpha=0.6
font_size=20

# Raccourcis clavier en jeu
# Maj Droite + F12 : Afficher / Masquer MangoHud
toggle_hud=Shift_R+F12
# Maj Droite + F11 : Changer la position (coin)
toggle_hud_position=Shift_R+F11
# Maj Droite + F9 : Réinitialiser les compteurs de 1% low
reset_fps_metrics=Shift_R+F9
