# #######################################################################################
#   AUTO-EXECUTION (STARTUP)
# #######################################################################################

##! Shell & UI
exec-once = noctalia                                                                      # Main Shell (Noctalia)
exec-once = /usr/lib/polkit-kde-authentication-agent-1                                    # Auth Agent
exec-once = systemctl --user import-environment XDG_SESSION_CLASS WAYLAND_DISPLAY DISPLAY # Export session vars to systemd
exec-once = systemctl --user start localsearch-3.service                                  # Tracker (required by Nautilus)
exec-once = sleep 2 && nautilus --gapplication-service 2>/dev/null                        # Nautilus (Pre-load in background for instant launch)

##! Input & Hardware
exec-once = hyprctl setcursor macOS 24                # Set Cursor Theme
exec-once = steam -silent                             # Steam (Background)
exec-once = jetbrain-fix                              # JetBrains Fix icon
exec-once = ~/.config/hypr/scripts/manage_workspaces.sh
exec-once = ~/.config/hypr/scripts/bitwarden-float.sh
exec-once = [workspace 1 silent] google-chrome-stable


