# #######################################################################################
#   AUTO-EXECUTION (STARTUP)
# #######################################################################################

##! Shell & UI
exec-once = noctalia                                  # Main Shell (Noctalia)
exec-once = warp-taskbar                              # Taskbar
exec-once = /usr/lib/polkit-kde-authentication-agent-1 # Auth Agent

##! Input & Hardware
exec-once = hyprctl setcursor macOS 24                # Set Cursor Theme
exec-once = steam -silent                             # Steam (Background)
