# #######################################################################################
# 📏  WINDOW & LAYER RULES
# #######################################################################################

##! Floating Rules
windowrule = match:title ^(Open File)(.*)$, float on
windowrule = match:title ^(Open File)(.*)$, center on
windowrule = match:title ^(Select a File)(.*)$, float on
windowrule = match:title ^(Select a File)(.*)$, center on
windowrule = match:title ^(Open Folder)(.*)$, float on
windowrule = match:title ^(Open Folder)(.*)$, center on
windowrule = match:title ^(Save As)(.*)$, float on
windowrule = match:title ^(Save As)(.*)$, center on

##! System Apps
windowrule = match:class ^(pavucontrol)$, float on
windowrule = match:class ^(pavucontrol)$, size (monitor_w*.45) (monitor_h*.45)
windowrule = match:class ^(pavucontrol)$, center on

##! Tiling & Special
windowrule = match:class ^dev\.warp\.Warp$, tile on
windowrule = match:float 0, no_shadow on

##! Fixes & Workarounds
# Tearing for games
windowrule = match:title .*\.exe, immediate on
windowrule = match:title .*minecraft.*, immediate on
windowrule = match:class ^(steam_app).*, immediate on

# Jetbrains Focus Fix
windowrule = match:class ^jetbrains-.*$, match:float 1, match:title ^$|^\s$|^win\d+$, no_initial_focus on
