# #######################################################################################
#   SPECIAL WORKSPACES (COMM & MUSIC)
# #######################################################################################

##! Discord (Communication)
windowrule {
  name = discord-special-workspace
  match:class = ^(discord)$
  workspace = special:comm silent
}

##! Spotify (Music)
windowrule {
  name = spotify-special-workspace
  match:class = ^(spotify)$
  workspace = special:music silent
}

##! Configuration
workspace = special:music, gapsout:50
workspace = special:comm, gapsout:50

##! Autostart Special Apps
exec-once = discord
exec-once = spotify
exec-once = sleep 5 && ~/.config/hypr/scripts/move-special.sh
