# #######################################################################################
#   SPECIAL WORKSPACES (COMM & MUSIC)
# #######################################################################################

##! Exclusion Rules (Kick out other apps)
windowrule {
    name = kick-out-comm
    match:workspace = name:special:comm
    workspace = previous
}

windowrule {
    name = kick-out-music
    match:workspace = name:special:music
    workspace = previous
}

##! Window Rules (Direct assignment)
windowrule {
    name = discord-comm
    match:class = ^(discord)$
    workspace = special:comm silent
}

windowrule {
    name = spotify-music
    match:class = ^(Spotify)$
    workspace = special:music silent
}

##! Workspace Configuration
workspace = special:music, gapsout:50
workspace = special:comm, gapsout:50

##! Autostart
exec-once = discord
exec-once = spotify